-- Create announcements table
create table if not exists announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  status text not null default 'active',
  priority text not null default 'normal',
  start_date timestamp with time zone not null default now(),
  end_date timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone
);

-- Enable RLS
alter table announcements enable row level security;

-- Create policies
create policy "Enable read access for all users" on announcements
  for select using (true);

create policy "Enable insert for authenticated users only" on announcements
  for insert with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only" on announcements
  for update using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users only" on announcements
  for delete using (auth.role() = 'authenticated'); 