-- Create blogs table
create table if not exists blogs (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  author_name text not null,
  image_id bigint references gallery_images(id),
  image_url text not null,
  published boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone
);

-- Enable RLS
alter table blogs enable row level security;

-- Drop existing policies if they exist
drop policy if exists "Enable read access for all users" on blogs;
drop policy if exists "Enable insert for authenticated users only" on blogs;
drop policy if exists "Enable update for authenticated users only" on blogs;
drop policy if exists "Enable delete for authenticated users only" on blogs;

-- Create policies
create policy "Enable read access for all users" on blogs
  for select using (true);

create policy "Enable insert for authenticated users only" on blogs
  for insert with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only" on blogs
  for update using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users only" on blogs
  for delete using (auth.role() = 'authenticated'); 