-- Create gallery_images table
create table if not exists gallery_images (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  image_url text not null,
  category text not null default 'general',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table gallery_images enable row level security;

-- Create policies
create policy "Enable read access for all users" on gallery_images
  for select using (true);

create policy "Enable insert for authenticated users only" on gallery_images
  for insert with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only" on gallery_images
  for update using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users only" on gallery_images
  for delete using (auth.role() = 'authenticated'); 