-- Create carousels table
create table if not exists carousels (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  image_id bigint references gallery_images(id),
  image_url text not null,
  section text not null default 'hero',
  display_order integer not null default 0,
  active boolean not null default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone
);

-- Enable RLS
alter table carousels enable row level security;

-- Drop existing policies if they exist
drop policy if exists "Enable read access for all users" on carousels;
drop policy if exists "Enable insert for authenticated users only" on carousels;
drop policy if exists "Enable update for authenticated users only" on carousels;
drop policy if exists "Enable delete for authenticated users only" on carousels;

-- Create policies
create policy "Enable read access for all users" on carousels
  for select using (true);

create policy "Enable insert for authenticated users only" on carousels
  for insert with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only" on carousels
  for update using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users only" on carousels
  for delete using (auth.role() = 'authenticated'); 